export const jobs = [
  {
    id: 1,
    title: "Social Media Assistant",
    company: "Nomad",
    location: "Paris, France",
    type: "Full-time",
    categories: ["Marketing", "Design"],
    applied: 5,
    capacity: 10,
    description:
      "Help manage social media platforms, create content, and engage with the community.",
    responsibilities: [
      "Community engagement to ensure representation online.",
      "Focus on social media content development and publication.",
      "Marketing and strategy support.",
      "Stay on top of trends on social media platforms.",
      "Engage with online communities.",
    ],
    requirements: [
      "Energy from people and creating ideal work environments.",
      "Detail-oriented and creative mindset.",
      "Growth marketer with experience running campaigns.",
    ],
    salary: "$75k-$85k USD",
  },
  {
    id: 2,
    title: "Brand Designer",
    company: "Dropbox",
    location: "San Francisco, USA",
    type: "Full-time",
    categories: ["Marketing", "Design"],
    applied: 2,
    capacity: 10,
    description: "Design creative assets for brand marketing campaigns.",
    responsibilities: [
      "Design marketing materials.",
      "Collaborate with teams.",
    ],
    requirements: ["Proficiency in design tools.", "Attention to detail."],
    salary: "$80k-$90k USD",
  },
  {
    id: 3,
    title: "Interactive Developer",
    company: "Terraform",
    location: "Hamburg, Germany",
    type: "Full-time",
    categories: ["Technology"],
    applied: 8,
    capacity: 12,
    description: "Develop engaging, interactive web experiences.",
    responsibilities: ["Build interactive UI components.", "Test and deploy."],
    requirements: ["Experience in React.", "Strong debugging skills."],
    salary: "$90k-$100k USD",
  },
  {
    id: 4,
    title: "Email Marketing",
    company: "Revolut",
    location: "Madrid, Spain",
    type: "Internship",
    categories: ["Marketing", "Design"],
    applied: 0,
    capacity: 10,
    description:
      "Plan and execute email campaigns to engage and retain customers.",
    responsibilities: [
      "Create email templates.",
      "Monitor campaign performance.",
    ],
    requirements: [
      "Basic marketing knowledge.",
      "Strong communication skills.",
    ],
    salary: "€25k-€30k",
  },
  {
    id: 5,
    title: "Lead Engineer",
    company: "Canva",
    location: "Ankara, Turkey",
    type: "Full-time",
    categories: ["Engineering"],
    applied: 5,
    capacity: 12,
    description: "Lead engineering teams to build scalable software.",
    responsibilities: [
      "Manage engineering teams.",
      "Define technical strategy.",
    ],
    requirements: ["Leadership experience.", "Strong technical expertise."],
    salary: "$120k-$140k USD",
  },
];
