export const jobs = [
  {
    id: 1,
    title: "Social Media Assistant",
    company: "Nomad",
    location: "Paris, France",
    type: "Full-time",

    categories: ["Marketing", "Design"],
    applied: 5,
    capacity: 10,
  },
  {
    id: 2,
    title: "Brand Designer",
    company: "Dropbox",
    location: "San Francisco, USA",
    type: "Full-time",
    categories: ["Marketing", "Design"],
    applied: 2,
    capacity: 10,
  },
  {
    id: 3,
    title: "Interactive Developer",
    company: "Terraform",
    location: "Hamburg, Germany",
    type: "Full-time",
    categories: ["Marketinge", "Design"],
    applied: 8,
    capacity: 12,
  },
  {
    id: 4,
    title: "Email Marketing",
    company: "Revolut",
    location: "Madrid, Spain",
    type: "Internship",
    categories: ["Marketing", "Design"],
    applied: 0,
    capacity: 10,
  },
  {
    id: 5,
    title: "Lead Engineer",
    company: "Canva",
    location: "Ankara, Turkey",
    type: "Full-time",
    categories: ["Engineering"],
    applied: 5,
    capacity: 12,
  },
  {
    id: 6,
    title: "Product Designer",
    company: "ClassPass",
    location: "Berlin, Germany",
    type: "Full-time",
    categories: ["Marketing", "Design"],
    applied: 5,
    capacity: 10,
  },
  {
    id: 7,
    title: "Customer Manager",
    company: "Pitch",
    location: "Rome, Italy",
    type: "Full-time",
    categories: ["Business"],
    applied: 5,
    capacity: 10,
  },
  {
    id: 8,
    title: "Java Developer",
    company: "GoDaddy",
    location: "Oslo, Sweden",
    type: "Part-time",
    categories: ["Technology"],
    applied: 5,
    capacity: 10,
  },
];
